name = "BOOP"
uuid = "3bb2f618-3363-4713-be1c-d56221b75334"
authors = ["Oskar Gustafsson"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GaussianProcesses = "891a1506-143c-57d2-908e-e1f8e92e6de9"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
LatinHypercubeSampling = "a5e1c1ea-c99a-51d3-a14d-a9a37257b02d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "0.25"
ForwardDiff = "1"
GaussianProcesses = "0.12.5"
KernelFunctions = "0.10.65"
LatinHypercubeSampling = "1.9.0"
LinearAlgebra = "1"
Optim = "1"
Plots = "1"
ProgressMeter = "1.11.0"
Random = "1"
Revise = "3.8.0"
SpecialFunctions = "2.5.1"
Statistics = "1"
StatsBase = "0.34.6"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
